// src/Whoami.jsx
import { createSignal, For } from "solid-js";
import { Typist } from "./Typist";

const info = {
  title1: "i can deliver : ",
  name: "I am mahmoud gamal eltahawy",
  job: "a fullstack developer",
  serivces: ["- desktop apps", "- web apps"],
};

export function Whoami() {
  const [name, set_name] = createSignal("");
  const [job, set_job] = createSignal("");
  const services_signals = info.serivces.map((_) => createSignal(""));
  const [title1, set_title1] = createSignal("");

  const typist = new Typist(50);

  typist.type(info.name, set_name);
  typist.type(info.job, set_job);
  typist.type(info.title1, set_title1);
  for (let i = 0; i < info.serivces.length; i++) {
    typist.type(
      info.serivces[i],
      services_signals[i][1],
    );
  }

  return (
    <section class="m-2">
      <div class="flex">
        <img
          loading="eager"
          src="me.jpg"
          alt="profile"
          class="img-animated w-[30%] rounded-full"
        />
        <section class="my-40 sm:mx-5 text-sm sm:text-3xl w-[85%] h-56 grid grid-cols-1 justify-left justify-items-left auto-rows-max">
          <p class="m-2 sm:my-4 sm:mt-5">{name()}</p>
          <p class="m-2 sm:my-4 sm:mt-5">{job()}</p>
          <p class="m-2 sm:my-4 sm:mt-5">{title1()}</p>
          <ol class="text-base sm:text-xl sm:my-14 sm:mt-5">
            <For each={info.serivces}>
              {(_, index) => {
                return (
                  <li class="sm:text-xl mx-10 sm:mt-5">
                    {services_signals[index()][0]()}
                  </li>
                );
              }}
            </For>
          </ol>
        </section>
      </div>
    </section>
  );
}

// src/app/whoami/whoami.component.ts
import { Component, OnInit, signal} from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { Typist } from '../utils/typist';
import { NgFor } from '@angular/common';


const c_services = ["desktop apps","web apps"]


@Component({
  selector: 'whoami',
  standalone: true,
  imports: [RouterOutlet,NgFor],
  templateUrl: './whoami.component.html',
})
export class WhoamiComponent implements OnInit {
  typist = new Typist(40)
  name = signal("")
  job = signal("")
  services_n = signal("")
  services = c_services.map((_) => signal(""));


  ngOnInit(): void {
    this.typist.type("my name is mahmoud gamal eltahawy",this.name)
    this.typist.type("a fullstack developer",this.job)
    this.typist.type("i can deliver : ",this.services_n)
    for(let i = 0; i < c_services.length;i++) {
      this.typist.type(c_services[i],this.services[i]);
    }
  }
}
const s = "hello world";


<section class="m-2">
  <div class="flex">
    <img loading="eager" src="./assets/me.jpg" alt="profile" class="img-animated w-[30%] rounded-full" />
    <section
      class="my-40 sm:mx-5 text-sm sm:text-3xl w-[85%] h-56 grid grid-cols-1 justify-left justify-items-left auto-rows-max">
      <p class="m-2 sm:my-4 sm:mt-5">{{name()}}</p>
      <p class="m-2 sm:my-4 sm:mt-5">{{job()}}</p>
      <p class="m-2 sm:my-4 sm:mt-5">{{services_n()}}</p>
      <ol class="text-base sm:text-xl sm:my-14 sm:mt-5">
        <li *ngFor="let service of services" class="sm:text-xl mx-10 sm:mt-5">{{service()}}</li>
      </ol>
    </section>
  </div>
</section>
